project:
  type: website

website:
  title: "Lego I"
  navbar:
    search: true
    left:
      - href: index.qmd
        text: Home
      - recursos.qmd
      - text: "Nivelamento"
        menu:
          - materiais/nivelamento1.qmd
      - text: "Aulas"
        menu:
          - materiais/aula1.qmd
      - text: "Listas"
        menu:
          - exercicios/exercicios1.qmd

    right:
      - href: http://www.github.com/meirelesff/lego1
        icon: github

format:
  html:
    theme: litera
    css: styles.css
    toc: true
    link-external-icon: true
    link-external-newwindow: true
